export const SAGA_POST_QUESTION = "SAGA_POST_QUESTION";
export const POST_QUESTION = "POST_QUESTION";

export const SAGA_LOAD_QUESTIONS = "SAGA_LOAD_QUESTIONS";
export const LOAD_QUESTIONS = "LOAD_QUESTIONS";

export const CHANGE_FEED_MODAL_STATUS = "CHANGE_FEED_MODAL_STATUS";
export const CHANGE_HEADER_MODAL_STATUS = "CHANGE_HEADER_MODAL_STATUS";

export const SAGA_AUTH = "SAGA_AUTH";
export const AUTH = "AUTH";

export const SAGA_LOGOUT = "SAGA_LOGOUT";
export const LOGOUT = "LOGOUT";
