export const SAGA_POST_QUESTION = "SAGA_POST_QUESTION";
export const POST_QUESTION = "POST_QUESTION";

export const SAGA_LOAD_QUESTIONS = "SAGA_LOAD_QUESTIONS";
export const LOAD_QUESTIONS = "LOAD_QUESTIONS";

export const LOAD_ANSWERS = "LOAD_ANSWERS";
export const SAGA_LOAD_ANSWERS = "SAGA_LOAD_ANSWERS";

export const CHANGE_FEED_MODAL_STATUS = "CHANGE_FEED_MODAL_STATUS";
export const CHANGE_HEADER_MODAL_STATUS = "CHANGE_HEADER_MODAL_STATUS";

export const SAGA_AUTH = "SAGA_AUTH";
export const AUTH = "AUTH";

export const SAGA_LOGOUT = "SAGA_LOGOUT";
export const LOGOUT = "LOGOUT";

export const LIKE_ANSWER = "LIKE_ANSWER";
export const SAGA_LIKE_ANSWER = "SAGA_LIKE_ANSWER";

export const LIKE_QUESTION = "LIKE_QUESTION";
export const SAGA_LIKE_QUESTION = "SAGA_LIKE_QUESTION";

export const SAGA_EDIT_PROFILE = "SAGA_EDIT_PROFILE";
export const EDIT_PROFILE = "EDIT_PROFILE";

export const SAGA_EDIT_QUESTION = "SAGA_EDIT_QUESTION";
export const EDIT_QUESTION = "EDIT_QUESTION";

export const CHANGE_REDIRECT_STATUS = "CHANGE_REDIRECT_STATUS";

export const SAGA_TOGGLE_TODO = "SAGA_TOGGLE_TODO";
export const TOGGLE_TODO = "TOGGLE_TODO";

export const SAGA_ADD_PROFILE_QA = "SAGA_ADD_PROFILE_QA";
export const ADD_PROFILE_QA = "ADD_PROFILE_QA";
